Remove wantErrFormatted
google/gce-tcb-verifier pull request #41
Opened 2024-09-03 15:15 UTC by deeglaze

2024-09-03 15:41 UTC, AdamCDunlap approved these changes

2024-09-03 16:10 UTC, deeglaze commented
Tests failing since the dev signing key expired September 1st. Regenerated.

2024-09-03 22:29 UTC, merged

2024-09-03 22:34 UTC, AdamCDunlap requested changes

2024-09-03 22:34 UTC, AdamCDunlap commented on sign/gcsca/gcsca.go
> +		fmt.Println("Root cert path", ca.RootPath)
is this debug string useful?

2024-09-03 22:34 UTC, AdamCDunlap commented on sign/gcsca/gcsca.go
>  	}
Add comment on this function that at least documents what the bool means.

2024-09-03 22:34 UTC, AdamCDunlap commented on sign/gcsca/gcsca.go
> +// and updates the given manifest to reflect the created object's entry. Returns whether any manifest
Comment is out of date -- no longer "returns whether any manifest changes happened"

2024-09-03 22:34 UTC, AdamCDunlap commented on sign/gcsca/gcsca.go
> +	fmt.Println("NEWOBJ", name)
debug print?

2024-09-03 22:34 UTC, AdamCDunlap commented on sign/gcsca/gcsca.go
> +		fmt.Println("OVERWRITE", name)
debug print?

2024-09-03 22:34 UTC, AdamCDunlap commented on sign/gcsca/gcsca.go
I don't see how the changes in this file reflect the commit message. Can you make sure the commit messages accurately reflect all the changes you're making and also why you're making them?

2024-09-04 02:19 UTC, deeglaze commented on sign/gcsca/gcsca.go
Yes, I unfortunately didn't amend the commit messages well enough, though I did try to keep different concepts in different commits. I'll clean up the code from your other comments in a follow-up PR.